# Generated by Django 3.2 on 2021-05-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='knowledge',
            fields=[
                ('cagr', models.FloatField()),
                ('highest', models.FloatField()),
                ('symbol', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
    ]
