# Generated by Django 3.2 on 2021-05-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledge',
            options={'verbose_name_plural': 'knowledge'},
        ),
    ]
