# Generated by Django 3.2 on 2021-05-22 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_knowledge_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='currentPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='lastRun',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
